#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'beautifulDays' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER i
#  2. INTEGER j
#  3. INTEGER k
#

def beautifulDays(i, j, k):
    # Variable to store number of beautiful days
    count = 0
    
    # List to store the reverse of each element in the input array
    reversed = []
    
    # Logic to find the reverse of a number
    for num in range(i,j+1) :
        rev = 0
        while num > 0 :
            rem = num % 10
            rev = (rev * 10) + rem
            num = num // 10
        reversed.append(rev)
    
    # Input array list
    input = list(range(i,j+1))
    
    # Logic to count number of beautiful days
    for i in range(len(reversed)) :
        if abs(input[i] - reversed[i]) % k == 0 :
            count = count + 1
            
    
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    i = int(first_multiple_input[0])

    j = int(first_multiple_input[1])

    k = int(first_multiple_input[2])

    result = beautifulDays(i, j, k)

    fptr.write(str(result) + '\n')

    fptr.close()
