#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    # Variable to store the minimum score at every stage
    minscore = scores[0]
    # Variable to store the maximum score at every stage
    maxscore = scores[0]
    # Variable to store the number of times she has broke her worst record
    minimum = 0
    # Variable to store the number of times she has broke her best record
    maximum = 0
    # Empty list to store the maximum & minimum number of times she has broke her record respectively
    result = []
    # Logic to record her performance
    for i in range(1,len(scores)) :
        if scores[i] > maxscore :
            maxscore = scores[i]
            maximum = maximum + 1
        elif scores[i] < minscore :
            minscore = scores[i]
            minimum = minimum + 1
           
    result.append(maximum)
    result.append(minimum)
    
    return result
    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
