#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'circularArrayRotation' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER k
#  3. INTEGER_ARRAY queries
#

def circularArrayRotation(a, k, queries):
    # Empty list to store the final values to return
    result = []
    # Variable to keep track of number of circular rotations done
    count = 1
    # Logic to circular rotate array of integers
    # 'insert()' right shifts rest of the elements
    # 'del()' will delete the element and preserve the original length of the array
    while count <= k :
        last = a[len(a) - 1]
        a.insert(0,last)
        del a[len(a) - 1]
        count = count + 1
    # Logic to return the elements after indexing from 'queries'
    for i in queries :
        result.append(a[i])
    
    return result
        
   
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    q = int(first_multiple_input[2])

    a = list(map(int, input().rstrip().split()))

    queries = []

    for _ in range(q):
        queries_item = int(input().strip())
        queries.append(queries_item)

    result = circularArrayRotation(a, k, queries)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
