#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    # Variable to check the sea level value
    level = 0
    # Variable to store the number of valleys walked through
    valley = 0
    # Dictionary to assign specific values to each character in the array
    d = {'U' : 1,'D' : -1}
    # Logic to find the number of valleys walked through
    for step in path :
        level = level + d[step]
        if level == 0 and step == 'U' :
            valley = valley + 1
            
    return valley

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
