#!/bin/python3

import os
import sys

#
# Complete the getMoneySpent function below.
#
def getMoneySpent(keyboards, drives, b):
    # Empty list to store combinations <= b 
    fresult = []
    # Empty list to store all combinations 
    result = []
    # Logic to store all combinations
    for key in keyboards :
        for drive in drives :
            result.append(key + drive)
    # Logic to store all combinations <= b
    for res in result :
        if res <= b :
            fresult.append(res)
    # Return conditions        
    if len(fresult) == 0 :
        return -1
    else :
        return max(fresult)
   
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    bnm = input().split()

    b = int(bnm[0])

    n = int(bnm[1])

    m = int(bnm[2])

    keyboards = list(map(int, input().rstrip().split()))

    drives = list(map(int, input().rstrip().split()))

    #
    # The maximum amount of money she can spend on a keyboard and USB drive, or -1 if she can't purchase both items
    #

    moneySpent = getMoneySpent(keyboards, drives, b)

    fptr.write(str(moneySpent) + '\n')

    fptr.close()
