#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'equalizeArray' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def equalizeArray(arr):
    # Empty list to store the number of deletions required to attain each element in the list
    result = []
    # Logic to find the number of deletions required to attain each element in the list
    for num in arr :
        numcount = arr.count(num)
        numdel = len(arr) - numcount
        result.append(numdel)
        
    return min(result)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = equalizeArray(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
