#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grades):
    # Write your code here
    for i in range(len(grades)) :
        # Grade < 38 means no round off
        if grades[i] < 38 :
            grades[i] = grades[i]
        # Round off & find next multiple of 5.Make sure mulof5 > grades[i] else mulof5 = mulof5 + 5
        else :
            rounded = round(grades[i]/5)
            mulof5 = rounded * 5
            if grades[i] > mulof5 :
                mulof5 = mulof5 + 5
            if abs(grades[i] - mulof5) < 3 :
                grades[i] = mulof5
            else :
                grades[i] = grades[i]
    return grades

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
