#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Variable to store the unsorted element
    p = arr[len(arr) - 1]
    # Index variable to right shift/copy when the test case fails
    j = len(arr) - 1
    # Variable index used for comparison at each stage
    i = len(arr) - 2
    # Logic to sort at each iteration
    while j > 0 and i >= 0 :
        if arr[i] > p :
            arr[j] = arr[i]
            j = j - 1
            i =  i - 1
            print(*arr)
        else :
            arr[i + 1] = p
            print(*arr)
            break
    # Special case checking   
    if j == 0 and i == -1 :
        arr[j] = p
        print(*arr)
    
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
