#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

#
# Complete the 'minimumDistances' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def minimumDistances(a):
    # Empty list to store the distance values of pairs
    result = []
    # Logic to find the distance values of pairs
    for i in range(len(a)) :
        for j in range(i + 1,len(a)) :
            if a[i] == a[j] :
                result.append(abs(j - i))
    # Return condition logic            
    if len(result) == 0 :
        return -1
    else :
        return min(result)
    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = minimumDistances(a)

    fptr.write(str(result) + '\n')

    fptr.close()
