#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the kangaroo function below.
def kangaroo(x1, v1, x2, v2):
    # Count to check for match
    count = 0
    # Loop to check till 10000 jumps
    for i in range(10000) :
        total1 = x1 + (v1 * i)
        total2 = x2 + (v2 * i)
        if total1 == total2 :
            count = count + 1
            break 
    if count == 1 :
        return 'YES'
    else :
        return 'NO'
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])

    v1 = int(x1V1X2V2[1])

    x2 = int(x1V1X2V2[2])

    v2 = int(x1V1X2V2[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()
