#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'quickSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def quickSort(arr):
    # Empty list to store the final result
    result = []
    # Empty list to store the elements lesser than p
    left = []
    # Empty list to store the elements greater than p
    right = []
    # Empty list to store the elements equal to p
    equal = []
    # Variable for the pivot element 
    p = arr[0]
    # Logic to append elements accordingly
    for num in arr :
        if num < p :
            left.append(num)
        elif num > p :
            right.append(num)
        else :
            equal.append(num)
    
    # Appending results based on the given instructions       
    for num in left :
        result.append(num)
        
    for num in equal :
        result.append(num)
        
    for num in right :
        result.append(num)
        
    return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = quickSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
